/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: markvini1972 (https://sketchfab.com/markvini1972)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/atx-coin-mrk-ver7-b24538b7943042a1aebeb661310e3012
Title: ATX_Coin_MRK_ver7
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const CoinModel = React.memo(function CoinModel(props) {
  const { nodes, materials } = useGLTF('/models/atx_coin_mrk_ver7-transformed.glb')
  const coinRef = useRef()
  const groupRef = useRef()

  useFrame(() => {
    //coinRef.current.rotation.y += 0.007;
    //groupRef.current.rotation.y += 0.007;
  });

  return (
    <group {...props} dispose={null}>
    <group
      //ref={groupRef}
      position={[0, -2, 0]} // Adjusted position to be more centered
      scale={[-2,3,2]} // Reduced scale for better fit
      //rotation={[0.4, -1, 0]} // Slight tilt for better viewing angle
    >
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="token_Atom" position={[220.508, 107.258, 19.15]}>
            <group
              name="pCylinder2"
              position={[-1.416, -3.635, 0.45]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.082}>
              <mesh
                name="pCylinder2_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.pCylinder2_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              name="detalhesqueficamverso"
              position={[-4.332, -4.351, -0.221]}
              scale={[0.87, 0.87, 0.131]}>
              <mesh
                name="detalhesqueficamverso_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhesqueficamverso_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              name="moeda"
              position={[0, 0, 0.137]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[4.999, 0.397, 4.999]}>
              <mesh
                name="moeda_Metal_2_0"
                castShadow
                receiveShadow
                geometry={nodes.moeda_Metal_2_0.geometry}
                material={materials.Metal_2}
              />
            </group>
            <group
              name="processadorverso"
              position={[-0.001, -0.086, 0.32]}
              scale={[2.396, 2.396, 1.2]}>
              <mesh
                name="processadorverso_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.processadorverso_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="tochangetheroworldverso" position={[0, -5.129, 0]}>
              <mesh
                name="tochangetheroworldverso_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.tochangetheroworldverso_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="tochangetheworldfrente" position={[0, -5.129, -0.045]}>
              <mesh
                name="tochangetheworldfrente_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.tochangetheworldfrente_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="thenextchanceverso" position={[0, -5.129, 0]}>
              <mesh
                name="thenextchanceverso_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.thenextchanceverso_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="thenextchantefrente" position={[0, -5.129, 0]}>
              <mesh
                name="thenextchantefrente_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.thenextchantefrente_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="detalhesquerda" position={[0, -5.129, 0]}>
              <mesh
                name="detalhesquerda_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhesquerda_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="esferas" position={[0, -5.129, 0]}>
              <mesh
                name="esferas_Metal_0_0"
                castShadow
                receiveShadow
                geometry={nodes.esferas_Metal_0_0.geometry}
                material={materials.Metal_0}
              />
            </group>
            <group name="processadorfrente" position={[0, -5.129, 0]}>
              <mesh
                name="processadorfrente_Metal_0_0"
                castShadow
                receiveShadow
                geometry={nodes.processadorfrente_Metal_0_0.geometry}
                material={materials.Metal_0}
              />
            </group>
            <group name="atxverso" position={[0, -5.129, 0]}>
              <mesh
                name="atxverso_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.atxverso_Metal_0.geometry}
                material={materials.Metal}
              />
              <mesh
                name="atxverso_Metal_2_0"
                castShadow
                receiveShadow
                geometry={nodes.atxverso_Metal_2_0.geometry}
                material={materials.Metal_2}
              />
            </group>
            <group name="Subdivision_Surface">
              <group name="energiacentro" position={[0, -5.129, 0]}>
                <mesh
                  name="energiacentro_Metal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.energiacentro_Metal_0.geometry}
                  material={materials.Metal}
                />
              </group>
            </group>
            <group name="detalhestopofrente" position={[0, -5.129, 0]}>
              <mesh
                name="detalhestopofrente_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhestopofrente_Metal_0.geometry}
                material={materials.Metal}
              />
              <mesh
                name="detalhestopofrente_Metal_0_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhestopofrente_Metal_0_0.geometry}
                material={materials.Metal_0}
              />
            </group>
            <group name="orbitas" position={[0, -5.129, 0]}>
              <mesh
                name="orbitas_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.orbitas_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group name="detalhequesai" position={[0, -5.129, 0]}>
              <mesh
                name="detalhequesai_Metal_1_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhequesai_Metal_1_0.geometry}
                material={materials.Metal_1}
              />
            </group>
            <group name="simbolo_polySurface74" position={[0, -5.129, 0]}>
              <mesh
                name="simbolo_polySurface74_Metal_0_0"
                castShadow
                receiveShadow
                geometry={nodes.simbolo_polySurface74_Metal_0_0.geometry}
                material={materials.Metal_0}
              />
            </group>
            <group name="detalhesbaixo" position={[0, -5.129, 0]}>
              <mesh
                name="detalhesbaixo_Metal_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhesbaixo_Metal_0.geometry}
                material={materials.Metal}
              />
              <mesh
                name="detalhesbaixo_Metal_0_0"
                castShadow
                receiveShadow
                geometry={nodes.detalhesbaixo_Metal_0_0.geometry}
                material={materials.Metal_0}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
    </group>
  )
});

export default CoinModel;
useGLTF.preload('/models/atx_coin_mrk_ver7-transformed.glb')