/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 eth_astronomical_pocket_set_1583.glb --transform 
Files: eth_astronomical_pocket_set_1583.glb [328.75MB] > C:\Users\pc\Downloads\eth_astronomical_pocket_set_1583-transformed.glb [23.66MB] (93%)
Author: ETH Library_Collections (https://sketchfab.com/ethlibrary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eth-astronomical-pocket-set-1583-76d156289b434509b513426438b923b5
Title: ETH: Astronomical pocket set, 1583
*/

"use client"
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const EthAstronomicalPocketSet1583 = React.memo(function EthAstronomicalPocketSet1583(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/eth_astronomical_pocket_set_1583-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="KGS_388_0_anim_null" position={[0, 9, 0]} rotation={[0.046, -Math.PI / 2, 0]}>
            <group name="Objekt_Nullposition_null" position={[0.289, 0.044, 0.175]} rotation={[-Math.PI / 2, 1.519, Math.PI / 2]}>
              <group name="KGS_388_0_Mittelscheibe_null" position={[0.175, -0.034, -0.291]} rotation={[0.051, -Math.PI / 2, 0]}>
                <group name="Mittelscheibe_custom" position={[0.282, 0.174, 0.181]} rotation={[-Math.PI / 2, 1.501, 1.565]}>
                  <group name="Hebel_Rotation_null" position={[0.349, 0.062, -1.812]} rotation={[-0.002, -0.422, -0.004]}>
                    <group name="Hebel">
                      <mesh name="Hebel_20230131_KGS-388-0_0" geometry={nodes['Hebel_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                    </group>
                  </group>
                  <group name="Schraube" position={[0.004, 0.074, -0.007]} rotation={[0.001, 0.306, -0.004]}>
                    <mesh name="Schraube_20230131_KGS-388-0_0" geometry={nodes['Schraube_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                  </group>
                  <mesh name="Mittelscheibe_custom_20230131_KGS-388-0_0" geometry={nodes['Mittelscheibe_custom_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                </group>
              </group>
              <group name="KGS_388_0_Basis" position={[0.175, -0.029, -0.291]} rotation={[0.051, -Math.PI / 2, 0]}>
                <mesh name="KGS_388_0_Basis_20230131_KGS-388-0_0" geometry={nodes['KGS_388_0_Basis_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
              </group>
              <group name="Drehachsen_Grundposition_null" position={[0, 0, -4.309]}>
                <group name="Drehachse_Deckel_oben_sfm_null" position={[0, 0.469, 0]} rotation={[0.082, 0.012, -0.011]}>
                  <group name="Drehachse_Deckel_oben_null" rotation={[0, 0, 0.015]}>
                    <group name="Skala_Rotation_null" position={[-0.015, 4.296, -0.052]}>
                      <group name="KGS_388_0_Skala">
                        <mesh name="KGS_388_0_Skala_20230131_KGS-388-0_0" geometry={nodes['KGS_388_0_Skala_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                      </group>
                    </group>
                    <group name="Deckel_oben_Achse">
                      <mesh name="Deckel_oben_Achse_20230131_KGS-388-0_0" geometry={nodes['Deckel_oben_Achse_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                    </group>
                    <group name="KGS_388_0_Deckel_oben">
                      <mesh name="KGS_388_0_Deckel_oben_20230131_KGS-388-0_0" geometry={nodes['KGS_388_0_Deckel_oben_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                    </group>
                  </group>
                </group>
                <group name="Drehachse_Deckel_unten_sfm_null" position={[0, -0.314, 0]} rotation={[-0.051, -0.063, 0.005]}>
                  <group name="Drehachse_Deckel_unten_null">
                    <group name="KGS_388_0_Blade_Rotation_null" position={[-0.535, -4.712, -0.254]} rotation={[-0.004, 0, -0.121]}>
                      <group name="KGS_388_0_Blade">
                        <mesh name="KGS_388_0_Blade_20230131_KGS-388-0_0" geometry={nodes['KGS_388_0_Blade_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                      </group>
                    </group>
                    <group name="Deckel_unten_Achse" position={[-0.005, -0.027, -0.049]} rotation={[0.001, 0.082, -0.075]}>
                      <mesh name="Deckel_unten_Achse_20230131_KGS-388-0_0" geometry={nodes['Deckel_unten_Achse_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                    </group>
                    <group name="KGS_388_0_Deckel_unten">
                      <mesh name="KGS_388_0_Deckel_unten_20230131_KGS-388-0_0" geometry={nodes['KGS_388_0_Deckel_unten_20230131_KGS-388-0_0'].geometry} material={materials['20230131_KGS-388-0']} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
});

export default EthAstronomicalPocketSet1583;
useGLTF.preload('/models/eth_astronomical_pocket_set_1583-transformed.glb')
