/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gabriel_Dja (https://sketchfab.com/Gabriel_Dja)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magic-stick-minecraft-6784a30676ae4d7794d40307f0fdfa47
Title: Magic Stick - Minecraft
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function MagicStick(props) {
  //const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/magic_stick_-_minecraft.glb')
  //const { actions } = useAnimations(animations, group)
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  return (
    <group ref={modelRef} {...props} dispose={null}
    scale={[3, 3, 3]}
    position={[0, -1, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="bone_1" position={[0, 1.188, 0]}>
                <group
                  name="b0999681-76b0-4727-5665-49e8d3cef13e_0"
                  rotation={[-0.654, -0.472, 0.536]}>
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['baton_magic_texture.png']}
                  />
                </group>
              </group>
              <group name="bone_3">
                <group name="56de0ef7-da08-aefb-1ea7-6ed4f37ec5c3_2" position={[0, 0.5, 0]}>
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['baton_magic_texture.png']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/magic_stick_-_minecraft.glb')