/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Adamante (https://sketchfab.com/Adamant6686)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sphere-and-rotated-rings-51792914ce6c442ca36153c4c06e55e5
Title: Sphere and rotated rings
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

const SphereModel = React.memo(function SphereModel(props) {
  const sphereRef = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sphere_and_rotated_rings.glb')
  
  useFrame((state, delta) => {
    if (sphereRef.current) {
      sphereRef.current.rotation.y += delta * 0.5;
      sphereRef.current.rotation.x += delta * 0.2;
    }
  })

  return (
    <group {...props} 
      ref={sphereRef}
      scale={0.0065} // Reduced scale further
      rotation={[0.2, 0, 0]}
      position={[0, 0.75, 0]} // Moved down slightly to center vertically
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="f85ff437812d471ca26a36bfdfd21a0efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="CINEMA_4D_Editor"
                  position={[658.618, 597.36, 558.515]}
                  rotation={[-Math.PI, 0.668, 2.551]}>
                  <group name="Object_5" />
                </group>
                <group name="Sphere">
                  <mesh
                    name="Sphere_Mat1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Mat1_0.geometry}
                    material={materials['Mat.1']}
                  />
                </group>
                <group name="Tube">
                  <mesh
                    name="Tube_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_1" rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="Tube_1_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_1_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_2" rotation={[0, 0, Math.PI / 2]}>
                  <mesh
                    name="Tube_2_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_2_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_3" rotation={[0, Math.PI / 2, 0]}>
                  <mesh
                    name="Tube_3_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_3_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_4" rotation={[0, Math.PI / 4, -Math.PI / 2]}>
                  <mesh
                    name="Tube_4_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_4_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_6" rotation={[0, Math.PI / 4, 0]}>
                  <mesh
                    name="Tube_6_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_6_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_5" rotation={[0, -Math.PI / 4, -Math.PI / 2]}>
                  <mesh
                    name="Tube_5_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_5_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Tube_7" rotation={[0, -Math.PI / 4, 0]}>
                  <mesh
                    name="Tube_7_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_7_Mat_0.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
});

export default SphereModel;
useGLTF.preload('/models/sphere_and_rotated_rings.glb')